version: '2'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod 
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod 
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    command: ["mongod", "--auth"]