version: '3'
services:
  client:
    image: 992382616033.dkr.ecr.us-east-1.amazonaws.com/datalous-client:latest
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: 992382616033.dkr.ecr.us-east-1.amazonaws.com/datalous-api:latest
    ports:
      - "8080:8080"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--auth"]

volumes:
  mongo-data:
    driver: local
