version: '2'
services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./client/src:/usr/src/client/src
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
