version: '2'
services:
  client:
    build: ./client
    ports:
      - '5173:5173'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
